// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlheajwvrpvyyjzyfqmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsaGVhand2cnB2eXlqenlmcW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTYyODgsImV4cCI6MjA2OTg5MjI4OH0.MdA2bcUIdp5-lyu4t0-vcvst2lJeOiPoxCLD5_DQJ1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});